# Generated by Django 2.2.6 on 2024-05-14 10:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Apointment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, null=True)),
                ('Date', models.CharField(max_length=120)),
                ('Time', models.CharField(max_length=300)),
                ('accepts', models.CharField(blank=True, default='Pending', max_length=150, null=True)),
                ('uu_id', models.UUIDField(default=uuid.uuid4)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=120, null=True)),
                ('matriculationnumber', models.CharField(blank=True, max_length=120, null=True)),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
                ('patients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa', to='user.patients')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
        migrations.CreateModel(
            name='Medical_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=500)),
                ('Weight', models.CharField(max_length=500)),
                ('blood_sugar', models.CharField(max_length=500)),
                ('body_tempreture', models.CharField(max_length=500)),
                ('medical_prescription', models.TextField(max_length=700)),
                ('u_id', models.UUIDField(default=uuid.uuid4)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('Book_Apointment_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Book_Apointment', to='doc.Book_Apointment_model')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.patients')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
        migrations.CreateModel(
            name='NurseModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Vital_Signs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=500, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=500, null=True)),
                ('admitted_date', models.CharField(blank=True, max_length=500, null=True)),
                ('discharged_date', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bookapointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookpoint', to='doc.Book_Apointment_model')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Send_report_to_pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=120, null=True)),
                ('Time_send', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='doc.Medical_test')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patients')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.CharField(default=False, max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Dr_notify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dr_notify', to='user.Doctors')),
                ('pq_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pq_message', to='user.patients')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Decline_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(max_length=500)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('book_apointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='doc.Book_Apointment_model')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
        migrations.CreateModel(
            name='confirm_drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.CharField(blank=True, default='Pending', max_length=120, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('drug_name', models.TextField(blank=True, max_length=500, null=True)),
                ('drug_price', models.CharField(blank=True, max_length=120, null=True)),
                ('Pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pham', to='user.Pham_model')),
                ('Send_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pham', to='doc.Send_report_to_pharmacy')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=90000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.CharField(default=True, max_length=500)),
                ('Sender_back', models.CharField(default=False, max_length=400)),
                ('reciever_back', models.CharField(default=False, max_length=400)),
                ('other_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='user.Doctors')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.patients')),
            ],
        ),
    ]
