# Generated by Django 2.2.6 on 2024-05-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240530_0707'),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursemodels',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve'),
        ),
    ]
