# Generated by Django 2.2.6 on 2024-05-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='med_history',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
