# Generated by Django 2.2.6 on 2024-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_patients_med_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatLeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
    ]
