# Generated by Django 2.2.6 on 2024-05-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_catleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant_model',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve'),
        ),
        migrations.AddField(
            model_name='patients',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve'),
        ),
        migrations.AddField(
            model_name='pham_model',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve'),
        ),
    ]
